// <auto-generated />
namespace StudentList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class migracja1234 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracja1234));
        
        string IMigrationMetadata.Id
        {
            get { return "201311211005585_migracja1234"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
